### ISSUE TITLE
Using the action `action-gh-release` instead of `curl`

### ISSUE THREAD

**Issue by gcarreno** [FranciscoDA/pacman#1]
Hey Francisco (@FranciscoDA),

Was going over who was using my `setup-lazarus` action and stumbled upon your game.

Had a look at your workflow file and noticed that upon a release, instead of using an action, you do it "_by hand_" with `curl`.

Can I please introduce you to [action-gh-release](https://github.com/softprops/action-gh-release)?
You can have a look on their repo how to use it, or, you can have a look at one of my [workflows](https://github.com/gcarreno/TestRestartApplication/blob/main/.github/workflows/build.yml) for an example.

Hope this helps!!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Francisco (@FranciscoDA),

Completely forgot to also mention the [upload-artifact](https://github.com/actions/upload-artifact) and the opposite [download-artifact](https://github.com/actions/download-artifact).

You'll find the use of them in the example I mentioned above.

Cheers,
Gus

**Comment by FranciscoDA** [comment]
Thank you @gcarreno
Turns out action-gh-release was the piece I was missing in the puzzle to create and upload the release assets.
I tried other solutions back when I initially wrote the workflow but none of them did quite work.

You can check the changes in this commit: e523f75

**Comment by gcarreno** [comment]
Hey @FranciscoDA,

I'm quite glad I could be of help!!

I use a bit more of the `actiion-gh-release` total amazing feature set.
I have a `release-notes.md` file that I update with the flow of programming and then use that as the release notes for the action.

Cheers,
Gus
